spring.application.name: order-service
spring.kafka:
  bootstrap-servers: b-1.practicemsk.q6n3il.c22.kafka.us-east-1.amazonaws.com:9094,b-2.practicemsk.q6n3il.c22.kafka.us-east-1.amazonaws.com:9094,b-3.practicemsk.q6n3il.c22.kafka.us-east-1.amazonaws.com:9094
  properties:
    security:
      protocol=SSL:
  producer:
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  streams:
    properties:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
      default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
      spring.json.trusted.packages: "*"
    state-dir: /tmp/kafka-streams/

management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
# Set a custom health URL
management.endpoints.web.base-path: /order-service
logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"